X00TD: doze: define LOCAL_OPTIONAL_USES_LIBRARIES
fixes:
error: mismatch in the <uses-library> tags between the build system and the manifest:
	- required libraries in build system: []
	                 vs. in the manifest: []
	- optional libraries in build system: []
	                 vs. in the manifest: [androidx.window.extensions, androidx.window.sidecar]
	- tags in the manifest (out/target/common/obj/APPS/Doze_intermediates/manifest/AndroidManifest.xml):
		<uses-library android:name="androidx.window.extensions" android:required="false"/>
		<uses-library android:name="androidx.window.sidecar" android:required="false"/>

Change-Id: I304f4b32833d00b9ddb89f07364144bb53bfae39
Signed-off-by: dotkit <ewprjkt@proton.me>